/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/coffeemug.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder1.geometry} material={nodes.Cylinder1.material} />
    </group>
  )
}

useGLTF.preload('/coffeemug.gltf')
