/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mouse-and-keyboard.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magic_mou2.geometry}
        material={nodes.Magic_mou2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard_b.geometry}
        material={nodes.Keyboard_b.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magic_mou1.geometry}
        material={nodes.Magic_mou1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard_1.geometry}
        material={nodes.Keyboard_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magic_mou0.geometry}
        material={nodes.Magic_mou0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard_0.geometry}
        material={nodes.Keyboard_0.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard_p.geometry}
        material={nodes.Keyboard_p.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magic_mous.geometry}
        material={nodes.Magic_mous.material}
      />
    </group>
  )
}

useGLTF.preload('/mouse-and-keyboard.gltf')