/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monitor.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={[-0.12, -1, -1.81]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/monitor.glb')
