/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lupapa (https://sketchfab.com/Lupapa)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mousepad-797d51312b64489c9501a40a4437f9e4
title: Mousepad
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mousepad.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert20SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/mousepad.glb')
