/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mouse.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Chocofur_Free_Accessories_05_1.geometry} material={materials['Chocofur_Free_Accessories_05.001']} />
        <mesh geometry={nodes.Chocofur_Free_Accessories_05_2.geometry} material={materials.Chocofur_Free_Accessories_05} />
        <mesh geometry={nodes.Chocofur_Free_Accessories_05_3.geometry} material={materials['Chocofur_Free_Accessories_05.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/mouse.glb')
