/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plant.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PEACE_LILLY_5K.geometry} material={materials.PEACE_LILLY_5K_Material_u1_v1} />
    </group>
  )
}

useGLTF.preload('/plant.glb')
