/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/plant.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.sansevieri.geometry}
        material={nodes.sansevieri.material}
        position={[0, -34.63, 0]}
        rotation={[Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.stones_vas.geometry}
        material={nodes.stones_vas.material}
        position={[0, -34.63, 0]}
        rotation={[Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.vase_red_0.geometry}
        material={nodes.vase_red_0.material}
        position={[0, -34.63, 0]}
        rotation={[Math.PI, 0, -Math.PI]}
      />
    </group>
  )
}

useGLTF.preload('/plant.gltf')