/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: emilsvfx (https://sketchfab.com/emilsvfx)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rubber-duck-a84cecb600c04eeba60d02f99b8b154b
title: Rubber Duck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rubberduck.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Duck} />
      </group>
    </group>
  )
}

useGLTF.preload('/rubberduck.glb')
