/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BeyondDigital (https://sketchfab.com/BeyondDigital)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rubiks-cube-d7d8aa83720246c782bca30dbadebb98
title: Rubik's Cube
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rubikscube.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Baked_baked_0.geometry} material={materials.baked} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rubikscube.glb')
